# This workflow updates Jira Fix Versions when PRs are merged to main.
# It extracts Jira issue keys (CAM-XXX) from the PR description's "Issues Closed" section
# and sets their Fix Version to "Current Release" via the Jira REST API.

name: Jira - Update Fix Versions

on:
  workflow_dispatch:
    inputs:
      test_issue:
        description: 'Test Jira issue key (e.g., CAM-123)'
        required: true
        type: string
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-fix-versions:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Jira Issues
        id: extract-issues
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "issues=${{ inputs.test_issue }}" >> $GITHUB_OUTPUT
          else
            PR_BODY="${{ github.event.pull_request.body }}"
            ISSUES=$(echo "$PR_BODY" | grep -oP 'CAM-\d+' | tr '\n' ' ')
            echo "issues=$ISSUES" >> $GITHUB_OUTPUT
          fi

      - name: Debug Token (Remove after use)
        run: echo "${{ secrets.JIRA_AUTH }}" | base64 --decode

      - name: Update Jira Fix Versions
        run: |
          for ISSUE in ${{ steps.extract-issues.outputs.issues }}; do
            curl --http1.1 -X PUT \
              -H "Authorization: Basic ${{ secrets.JIRA_AUTH }}" \
              -H "Content-Type: application/json" \
              "https://gobrio.atlassian.net/rest/api/3/issue/$ISSUE" \
              --data-raw "{
                \"fields\": {
                  \"fixVersions\": [
                    {
                      \"name\": \"Current Release\"
                    }
                  ]
                }
              }" -v || echo "Failed to update issue $ISSUE."
          done

